spring:
  application:
    name: synclog

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 100
    properties:
      hibernate:
        format_sql: false

  ai:
    huggingface:
      chat:
        api-key: ${HF_API_KEY}
        enabled: true
        url: https://router.huggingface.co/hf-inference/openai/gpt-oss-120b